"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ExternalLink } from "lucide-react";
import { Reveal } from "@/components/motion/reveal";

const descriptions = {
  retention: {
    DATA: "Validated customer inputs and consistent preprocessing.",
    MODEL: "Churn probability generated by the production classifier.",
    EXPLAIN: "Customer-level SHAP explanations show what is driving risk.",
    DECIDE: "Risk and business context become prioritised retention action.",
  },
  knowledge: {
    RETRIEVE: "Relevant enterprise evidence is surfaced from the knowledge scope.",
    RANK: "Relevance and authority reduce noisy context before reasoning.",
    REASON: "Specialised routes handle retrieval, policy and hybrid research tasks.",
    VERIFY: "Grounding checks confirm the final answer against supporting evidence.",
  },
} as const;

export function ProjectShowcase({
  number,
  title,
  kicker,
  description,
  href,
  liveHref,
  metrics,
  flow,
  tone,
}: {
  number: string;
  title: string;
  kicker: string;
  description: string;
  href: string;
  liveHref: string;
  metrics: [string, string][];
  flow: string[];
  tone: "retention" | "knowledge";
}) {
  const [active, setActive] = useState(0);
  const activeStage = flow[active];
  const activeDescription =
    descriptions[tone][activeStage as keyof (typeof descriptions)[typeof tone]];

  return (
    <Reveal>
      <article className={`project-showcase project-showcase-v2 project-${tone}`}>
        <div className="project-topline">
          <span>{number}</span>
          <span>{kicker}</span>
        </div>

        <div className="project-main-grid">
          <div className="project-copy">
            <h3>{title}</h3>
            <p>{description}</p>

            <div className="metric-row">
              {metrics.map(([value, label]) => (
                <div key={label} className="metric">
                  <strong>{value}</strong>
                  <span>{label}</span>
                </div>
              ))}
            </div>

            <div className="project-action-row project-action-row-ux">
              <div className="project-action">
                <Link href={href} className="text-link project-link">
                  Explore case study <ArrowRight size={16} />
                </Link>
                <small>Architecture, decisions & results</small>
              </div>

              <div className="project-action">
                <a
                  href={liveHref}
                  target="_blank"
                  rel="noreferrer"
                  className="text-link project-live-link"
                >
                  Open live product <ExternalLink size={15} />
                </a>
                <small>Try the deployed system</small>
              </div>
            </div>
          </div>

          <div className="project-visual project-visual-v2" aria-label={`${title} system flow`}>
            <div className="project-visual-header">
              <span>HOW IT WORKS</span>
              <span>SELECT A STAGE</span>
            </div>

            <div className="flow-list flow-list-v2">
              {flow.map((item, index) => (
                <button
                  className={
                    active === index
                      ? "flow-node flow-node-v2 active"
                      : "flow-node flow-node-v2"
                  }
                  key={item}
                  onClick={() => setActive(index)}
                  aria-pressed={active === index}
                >
                  <span>0{index + 1}</span>
                  <strong>{item}</strong>
                  <i aria-hidden="true">{active === index ? "●" : "→"}</i>
                </button>
              ))}
            </div>

            <div className="flow-detail flow-detail-ux" aria-live="polite">
              <span>WHY THIS STAGE MATTERS</span>
              <strong>{activeStage}</strong>
              <p>{activeDescription}</p>
            </div>
          </div>
        </div>
      </article>
    </Reveal>
  );
}
